# Describes the format for available phoenix_contact services
set_charging_current:
  description: Sets charging current.
  fields:
    entity_id:
      description: Name(s) of the entities to set
      example: "phoenix_contact.id"
    current:
      description: Charging current in Amperes
      example: "10"

enable_charging:
  description: Enable charging.
  fields:
    entity_id:
      description: Name(s) of the entities to set
      example: "phoenix_contact.id"

disable_charging:
  description: Disable charging.
  fields:
    entity_id:
      description: Name(s) of the entities to set
      example: "phoenix_contact.id"
